name: Deploy Visualizer

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'
      - run: echo "Installing dependencies"
      - run: bun install
      - run: echo "Building"
      - run: bun run build
      - uses: reggionick/s3-deploy@v4
        with:
          folder: app/dist
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: us-east-1
