name: Infra Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_clickhouse_password: ${{ secrets.TF_VAR_clickhouse_password }}
    steps:
      - uses: actions/checkout@v4
      - run: make
