name: Infra Continuous Integration

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Run type
        required: true
        default: "DRY"
        options:
          - DRY
          - REAL
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_clickhouse_password: ${{ secrets.TF_VAR_clickhouse_password }}
    steps:
      - uses: actions/checkout@v4
      - name: "Terraform Plan"
        run: make clickhouse_password="${TF_VAR_clickhouse_password}"
      - name: "Terraform Apply"
        if: inputs.type == 'REAL'
        run: make applyonly
